"""
Copyright (c) 2020, the Decred developers
See LICENSE for details
"""

from decred.dcr.agenda import Agenda, AgendaChoices, AgendaInfo, AgendasInfo


AGENDA_INFO_RAW = dict(status="defined", since=1, starttime=2, expiretime=3)
# Parsed values are the same as the raw ones.
AGENDA_INFO_PARSED = AGENDA_INFO_RAW
AGENDA_INFO_ATTRS = (
    "status",
    "since",
    "startTime",
    "expireTime",
)


def test_agenda_info():
    do_test(
        AgendaInfo, AGENDA_INFO_RAW, AGENDA_INFO_PARSED, AGENDA_INFO_ATTRS,
    )


AGENDA_CHOICES_RAW = dict(
    id="choices_id",
    description="description",
    bits=0,
    isabstain=False,
    isno=False,
    count=0,
    progress=0.0,
)
# Parsed values are the same as the raw ones.
AGENDA_CHOICES_PARSED = AGENDA_CHOICES_RAW
AGENDA_CHOICES_ATTRS = (
    "id",
    "description",
    "bits",
    "isAbstain",
    "isNo",
    "count",
    "progress",
)


def test_agenda_choices():
    do_test(
        AgendaChoices, AGENDA_CHOICES_RAW, AGENDA_CHOICES_PARSED, AGENDA_CHOICES_ATTRS,
    )


AGENDA_RAW = dict(
    id="agenda_id",
    description="description",
    mask=0,
    starttime=0,
    expiretime=0,
    status="status",
    quorumprogress=0.0,
    choices=[AGENDA_CHOICES_RAW],
)
# Make a copy of the raw dict in order not to overwrite it.
AGENDA_PARSED = dict(AGENDA_RAW)
AGENDA_PARSED["choices"] = [AgendaChoices.parse(AGENDA_CHOICES_RAW)]
AGENDA_ATTRS = (
    "id",
    "description",
    "mask",
    "startTime",
    "expireTime",
    "status",
    "quorumProgress",
    "choices",
)


def test_agenda():
    do_test(
        Agenda, AGENDA_RAW, AGENDA_PARSED, AGENDA_ATTRS,
    )


AGENDAS_INFO_RAW = {
    "currentheight": 0,
    "startheight": 0,
    "endheight": 0,
    "hash": "hash",
    "voteversion": 0,
    "quorum": 0.0,
    "totalvotes": 0,
    "agendas": [AGENDA_RAW],
}
# Make a copy of the raw dict in order not to overwrite it.
AGENDAS_INFO_PARSED = dict(AGENDAS_INFO_RAW)
AGENDAS_INFO_PARSED["agendas"] = [Agenda.parse(AGENDA_RAW)]
AGENDAS_INFO_ATTRS = (
    "currentHeight",
    "startHeight",
    "endHeight",
    "hash",
    "voteVersion",
    "quorum",
    "totalVotes",
    "agendas",
)


def test_agendas_info():
    do_test(
        AgendasInfo, AGENDAS_INFO_RAW, AGENDAS_INFO_PARSED, AGENDAS_INFO_ATTRS,
    )


def do_test(class_, raw, parsed, attrs):
    """
    Iterate over the attributes defined in <class_>_ATTRS and make sure that
    the values generated by its "parse" method are the same as the ones in
    <class_>_PARSED.

    Separate <class_>_ATTRS tuples are needed because the attribute names are
    different from the keys of the dicts the values are gotten from.
    """
    obj = class_.parse(raw)
    for attr in attrs:
        assert getattr(obj, attr) == parsed[attr.lower()]


def test_eq():
    # AgendaChoices
    choices = AgendaChoices.parse(AGENDA_CHOICES_RAW)
    assert choices != object()
    assert choices == choices

    # Agenda
    agenda = Agenda.parse(AGENDA_RAW)
    assert agenda != object()
    assert agenda == agenda
